apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - gateway.yml
  - service.yml
  - virtualService.yml

namespace: default

commonLabels:
  app: hello
  env: dev
